### ISSUE TITLE
Incorrect response from LLM Model

### ISSUE THREAD

**Issue by Mohammedvaraliya** [MVLU-Bot/frontend#7]
I've submitted "he" from the landing page, the LLM response appears to be out of context. While the response is related to our database, we need it to be more accurate and relevant. Our goal is to ensure that the system can handle inputs with insufficient context and still provide precise and appropriate responses.

Here's a snapshot of the encountered issue:

![image](https://github.com/user-attachments/assets/94a55a56-c83c-4647-bd88-dda8986958a9)

**Comment by subhashish-clg** [comment]
This issues is related to the backend. So I am closing this issue here. Please create the issue in `backend` repository.
